nameSpace: helm

nginx:
  replicaCount: 1
  image:
    account: ilhemb
    repository: nginx-service
    tag: latest
  service:
    type: NodePort
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30010

