apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: {{ .Values.nginx.replicaCount }} 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.account }}/{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          ports:
            - containerPort: {{ .Values.nginx.service.targetPort }}
      initContainers:
        - name: init-nginx
          image: busybox:1.28
          command: ['sh', '-c', 'echo The gateway is running! && sleep 60']              
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.nameSpace }}
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app: nginx
  ports:
    - protocol: {{ .Values.nginx.service.protocol }}
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      nodePort: {{ .Values.nginx.service.nodePort }}
---
